// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview A career summary/objective generator AI agent.
 *
 * - generateCareerSummary - A function that handles the career summary generation process.
 * - GenerateCareerSummaryInput - The input type for the generateCareerSummary function.
 * - GenerateCareerSummaryOutput - The return type for the generateCareerSummary function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateCareerSummaryInputSchema = z.object({
  skills: z
    .string()
    .describe('List of skills, separated by commas, relevant to the job.'),
  experience: z.string().describe('Description of work experience.'),
  desiredRole: z.string().describe('The desired job role or industry.'),
});
export type GenerateCareerSummaryInput = z.infer<
  typeof GenerateCareerSummaryInputSchema
>;

const GenerateCareerSummaryOutputSchema = z.object({
  careerSummary: z
    .string()
    .describe('A personalized career summary or objective statement.'),
});
export type GenerateCareerSummaryOutput = z.infer<
  typeof GenerateCareerSummaryOutputSchema
>;

export async function generateCareerSummary(
  input: GenerateCareerSummaryInput
): Promise<GenerateCareerSummaryOutput> {
  return generateCareerSummaryFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateCareerSummaryPrompt',
  input: {schema: GenerateCareerSummaryInputSchema},
  output: {schema: GenerateCareerSummaryOutputSchema},
  prompt: `You are a resume writing expert. Generate a compelling career summary or objective statement based on the provided skills, experience, and desired role.

Skills: {{{skills}}}
Experience: {{{experience}}}
Desired Role: {{{desiredRole}}}

Career Summary:`,
});

const generateCareerSummaryFlow = ai.defineFlow(
  {
    name: 'generateCareerSummaryFlow',
    inputSchema: GenerateCareerSummaryInputSchema,
    outputSchema: GenerateCareerSummaryOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
