import {
  User,
  Briefcase,
  GraduationCap,
  Sparkles,
  Lightbulb,
  PenSquare,
  Download,
  Palette,
  Printer,
  Trash2,
  ArrowUp,
  ArrowDown,
  Plus,
  FileJson,
  Moon,
  Sun,
  Laptop,
  Mail,
  Phone,
  MapPin,
  Link as LinkIcon,
} from 'lucide-react';

export const Icons = {
  user: User,
  briefcase: Briefcase,
  graduationCap: GraduationCap,
  sparkles: Sparkles,
  lightbulb: Lightbulb,
  pen: PenSquare,
  download: Download,
  palette: Palette,
  print: Printer,
  trash: Trash2,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  add: Plus,
  json: FileJson,
  moon: Moon,
  sun: Sun,
  laptop: Laptop,
  mail: Mail,
  phone: Phone,
  mapPin: MapPin,
  link: LinkIcon,
};
