import {
  User,
  Briefcase,
  GraduationCap,
  Sparkles,
  Lightbulb,
  PenSquare,
  Download,
  Palette,
  Printer,
  Trash2,
  ArrowUp,
  ArrowDown,
  Plus,
  FileJson,
  Moon,
  Sun,
  Laptop,
  Mail,
  Phone,
  MapPin,
  Link as LinkIcon,
  Check,
  ArrowLeft,
  ArrowRight,
  Lock,
  ChevronDown,
  ZoomIn,
  ZoomOut,
  CheckCircle,
  Search,
  Menu,
  X,
  FileText,
  Users,
  Activity,
  Star,
  Heart,
  Filter,
  LayoutGrid,
  List,
  Pen,
  Copy,
  Trash
} from 'lucide-react';

export const Icons = {
  user: User,
  briefcase: Briefcase,
  graduationCap: GraduationCap,
  sparkles: Sparkles,
  lightbulb: Lightbulb,
  pen: Pen,
  download: Download,
  palette: Palette,
  print: Printer,
  trash: Trash2,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  add: Plus,
  json: FileJson,
  moon: Moon,
  sun: Sun,
  laptop: Laptop,
  mail: Mail,
  phone: Phone,
  mapPin: MapPin,
  link: LinkIcon,
  check: Check,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  lock: Lock,
  chevronDown: ChevronDown,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
  checkCircle: CheckCircle,
  search: Search,
  menu: Menu,
  close: X,
  fileText: FileText,
  users: Users,
  activity: Activity,
  star: Star,
  heart: Heart,
  filter: Filter,
  layoutGrid: LayoutGrid,
  list: List,
  copy: Copy,
};
